#if !canImport(ObjectiveC)
import XCTest

extension WebsiteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebsiteTests = [
        ("testGenerate_Failure", testGenerate_Failure),
        ("testGenerate_Success", testGenerate_Success),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WebsiteTests.__allTests__WebsiteTests),
    ]
}
#endif
