name: Integrate

on:
  push:
    branches:
      - master

jobs:
  integrate:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Integrate
      run: sh integrate.sh
