name: Integrate

on:
  push:
    branches:
      - main

jobs:
  integrate-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Integrate
      run: sh integrate.sh

  integrate-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Integrate
      run: swift run
