name: Integrate

on:
  push:
    branches:
      - master

jobs:
  integrate-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Integrate
      run: sh integrate.sh

  integrate-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test
